name: Retry Release
on:
  workflow_dispatch:
    inputs:
      release:
        description: The Grails Release (e.g. 5.0.3)
        required: true
      target_branch:
        description: The Target Branch (e.g. 5.0.x)
        required: true
permissions: {}
jobs:
  release:
    permissions:
      contents: write  #  to create release
      issues: read  #  to get closed issues

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['11']
    env:
      GIT_USER_NAME: puneetbehl
      GIT_USER_EMAIL: behlp@objectcomputing.com
      GRADLE_OPTS: -Xmx1500m -Dfile.encoding=UTF-8
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: "v${{ github.event.inputs.release }}"
          token: ${{ secrets.GH_TOKEN }}
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
      - name: Extract Target Branch
        id: extract_branch
        run: |
          echo $TARGET_BRANCH
          echo ::set-output name=value::${TARGET_BRANCH}
        env:
          TARGET_BRANCH: ${{ github.event.inputs.target_branch }}
      - name: Set the current release version
        id: release_version
        run: echo ::set-output name=release_version::${VERSION}
        env:
          VERSION: ${{ github.event.inputs.release }}
      - name: Generate Groovydoc
        id: groovydoc
        uses: gradle/gradle-build-action@842c587ad8aa4c68eeba24c396e15af4c2e9f30a # v2
        env:
          GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
          GRADLE_ENTERPRISE_BUILD_CACHE_NODE_USER: ${{ secrets.GRADLE_ENTERPRISE_BUILD_CACHE_NODE_USER }}
          GRADLE_ENTERPRISE_BUILD_CACHE_NODE_KEY: ${{ secrets.GRADLE_ENTERPRISE_BUILD_CACHE_NODE_KEY }} ASZWQZQQWQWS
        with:
          arguments: groovydoc
      - name: Publish to Github Pages
        id: docs
        if: steps.groovydoc.outcome == 'success'
        uses: micronaut-projects/github-pages-deploy-action@grails
        env:
          BETA: ${{ contains(steps.release_version.outputs.release_version, 'M') || contains(steps.release_version.outputs.release_version, 'RC') }}
          SKIP_SNAPSHOT: ${{ startsWith(steps.extract_branch.outputs.value, '3.3') || startsWith(steps.extract_branch.outputs.value, '4.1') || startsWith(steps.extract_branch.outputs.value, '6.0') }}
          TARGET_REPOSITORY: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build/docs
          DOC_FOLDER: gh-pages
          COMMIT_EMAIL: behlp@objectcomputing.com
          COMMIT_NAME: Puneet Behl
          VERSION: ${{ steps.release_version.outputs.release_version }}
      - name: Run post-release
        if: steps.groovydoc.outcome == 'success'
        uses: micronaut-projects/github-actions/post-release@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          SNAPSHOT_SUFFIX: -SNAPSHOT
          TARGET_BRANCH: ${{ github.event.inputs.target_branch }}
          RELEASE_VERSION: ${{ github.event.inputs.release }}